### ISSUE TITLE
Om mau tanya.

### ISSUE THREAD

**Issue by twuh** [anggit97/flutter-tixid-clonning#1]
Om agit tertarik ga gabung di tim twuh buat jadi cto, cuman kita masih baru, no sallary untuk skrng, paling bisa kasih share, total sharenya bisa kita diskusikan berapa na.

**Comment by anggit97** [comment]
Hi twuh.

Makasih atas tawarannya. Kalo boleh tau twuh itu apa ya?

**Comment by twuh** [comment]
Micro financing marketplace wa kalau singkat na. Kita memudahkan pengguna untuk buat paket pinjaman(Kreditur) dan peminjam(Debitur) dalam satu aplikasi. Kalau penjelasan singkatnya ada di web https://twuh.me. 
Untuk ngobrol lebih lanjut boleh minta kontak line nya ga wa? 
Thanks

**Comment by anggit97** [comment]
Makasih sebelumnya atas tawarannya, tapi mohon maaf mas, saya tidak bisa ikut gabung ke startup mas.karena goals yg kita capai berbeda mas. Maaf ya mas.

**Comment by twuh** [comment]
Okay siap juragan. thanks juga buat respon cepatna.
